---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  vars:
    install_root_cert_pem: files/rootCA.pem
  roles:
    - role: prereq
    - role: download
    - role: gametize.install-root-cert

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: localhost
  connection: local
  roles:
    - role: postconfig/localhost
