---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  vars:
    install_root_cert_pem: files/rootCA.pem
    inotify_max_user_watches: 524288
    inotify_max_user_instances: 8192
  roles:
    - role: prereq
    - role: download
    - role: gametize.install-root-cert
    - role: gantsign.inotify

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: red
  become: yes
  roles:
    - role: red

- hosts: localhost
  connection: local
  roles:
    - role: postconfig/localhost
