---
k3s_version: v1.23.4+k3s1
# this is the user that has ssh access to these machines
ansible_user: debian
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "America/Los_Angeles"

# interface which will be used for flannel
flannel_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "10.10.0.10"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "some-SUPER-DEDEUPER-secret-password"

# change these to your liking, the only required one is--no-deploy servicelb
extra_server_args: "--disable servicelb --disable traefik --disable local-storage --etcd-s3 --etcd-s3-bucket=etcd-snapshot --etcd-s3-endpoint=minio.ericxliu.me:443 --etcd-s3-access-key=BHKZ6DPIFiIdQdUw616BwoQK78jNJdlkSYfncJRPtYPXpyeutJNC8fhyRGykgHTD --etcd-s3-secret-key=xJmDcrNbDJB0vFpliuz3bbe5bpvXhfIIzFf31mg6VnCYQUf697eyHtmM2B8KPBGq"
extra_agent_args: ""

# image tag for kube-vip
kube_vip_tag_version: "v0.4.3"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.12.1"
metal_lb_controller_tag_version: "v0.12.1"

# metallb ip range for load balancer
metal_lb_ip_range: "10.10.0.15-10.10.0.19"

copy_kubeconfig: true
